print("Hello World!")
print("Hello again")
print("I like typing like this")
print("This is fun")
print('Yay! Printing.')
# print("Is it reALLY PRINTING")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print#(octothorpe is this going to work?")
